name: Update Data Every 30 Minutes

on:
  push:
  schedule:
    - cron: '*/30 * * * *'  # Каждые 5 минут
  workflow_dispatch:  # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run parser
      run: |
        python scripts/main.py
        ls -la data/
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/out.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data $(date)"
        git push
